name : CI 

on:
  push:
    Branch:
      - main
  pull_request:
    Branch:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: install dependencies
      run:
        python -m pip install --upgrade pip
        python -m pip install pytest streamlit


    - name: run test
      run:
        pytest test.py
